#!/bin/bash
# Generate a Dockerfile template from the active or discovered Python venv with pinned package versions.

set -euo pipefail

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default to current directory if not specified
TARGET_REPO="${1:-.}"

# Resolve to absolute path
if [[ "$TARGET_REPO" != /* ]]; then
    TARGET_REPO="$(cd "$TARGET_REPO" && pwd)"
fi

# Verify the target is a directory
if [[ ! -d "$TARGET_REPO" ]]; then
    echo "Error: Target repository not found: $TARGET_REPO" >&2
    exit 1
fi

# Create .dev-shell directory if it doesn't exist
DEV_SHELL_DIR="$TARGET_REPO/.dev-shell"
mkdir -p "$DEV_SHELL_DIR"

# Determine the subsystem (mimics the framework's logic)
SUBSYSTEM="${MSYSTEM:-UCRT64}"  # Default to UCRT64 if not set

# Helper function to find preferred venv
find_venv() {
    local repo="$1"
    local subsys="$2"
    
    # Check repo-local .venv-<subsystem>
    if [[ -f "$repo/.venv-$subsys/bin/python" ]]; then
        echo "$repo/.venv-$subsys/bin/python"
        return 0
    fi
    
    # Check repo-local .venv
    if [[ -f "$repo/.venv/bin/python" ]]; then
        echo "$repo/.venv/bin/python"
        return 0
    fi
    
    # Check global .venv-<subsystem>
    if [[ -f "$HOME/.venv-$subsys/bin/python" ]]; then
        echo "$HOME/.venv-$subsys/bin/python"
        return 0
    fi
    
    # Check global .venv
    if [[ -f "$HOME/.venv/bin/python" ]]; then
        echo "$HOME/.venv/bin/python"
        return 0
    fi
    
    # Return empty if none found
    return 1
}

# Try to find a venv
VENV_PYTHON=""
if VENV_PYTHON=$(find_venv "$TARGET_REPO" "$SUBSYSTEM"); then
    echo "Using venv: $VENV_PYTHON"
    PYTHON_CMD="$VENV_PYTHON"
elif command -v python >/dev/null 2>&1; then
    echo "No venv found, using system Python"
    PYTHON_CMD="python"
else
    echo "Error: No Python venv found and no system Python available." >&2
    echo "Checked:" >&2
    echo "  - $TARGET_REPO/.venv-$SUBSYSTEM" >&2
    echo "  - $TARGET_REPO/.venv" >&2
    echo "  - $HOME/.venv-$SUBSYSTEM" >&2
    echo "  - $HOME/.venv" >&2
    exit 1
fi

# Get Python version
PYTHON_VERSION=$("$PYTHON_CMD" --version 2>&1 | awk '{print $2}')

# Freeze current venv packages
REQUIREMENTS="$DEV_SHELL_DIR/requirements.txt"
echo "Exporting packages from $PYTHON_CMD to $REQUIREMENTS..."
"$PYTHON_CMD" -m pip freeze > "$REQUIREMENTS"

# Count packages
PACKAGE_COUNT=$(wc -l < "$REQUIREMENTS")
echo "Exported $PACKAGE_COUNT packages."

# Generate Dockerfile template
DOCKERFILE="$DEV_SHELL_DIR/Dockerfile"
echo "Generating $DOCKERFILE..."

cat > "$DOCKERFILE" << 'EOF'
# Dockerfile - Generated by generate-dockerfile.sh
# This image freezes the Python environment for reproducible paper experiments.
# Build: docker build -t my-project-dev:latest .
# Run:   run-container.sh python scripts/run_experiment.py

ARG PYTHON_VERSION=3.12
FROM python:${PYTHON_VERSION}-slim

WORKDIR /workspace

# Copy requirements and install pinned packages
COPY .dev-shell/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy repo contents
COPY . .

# Set up entry point (optional, can be overridden)
# ENTRYPOINT ["python"]
# CMD ["--version"]
EOF

# Find the framework's templates directory (parent of this script's repo)
SCRIPT_REPO_ROOT="$(cd "$SCRIPT_DIR" && git rev-parse --show-toplevel 2>/dev/null || echo "$SCRIPT_DIR/../../../..")"
TEMPLATES_DIR="$SCRIPT_REPO_ROOT/templates"

# Copy HOWTO_REPRODUCE.md if it exists
if [[ -f "$TEMPLATES_DIR/HOWTO_REPRODUCE.md" ]]; then
    HOWTO_PATH="$TARGET_REPO/HOWTO_REPRODUCE.md"
    cp "$TEMPLATES_DIR/HOWTO_REPRODUCE.md" "$HOWTO_PATH"
    echo "✓ Copied HOWTO_REPRODUCE.md to: $HOWTO_PATH"
else
    echo "⚠ HOWTO_REPRODUCE.md template not found at $TEMPLATES_DIR (optional)"
fi

echo "✓ Dockerfile created at: $DOCKERFILE"
echo ""
echo "Next steps:"
echo "  1. Edit $DOCKERFILE to customize the base image or add dependencies"
echo "  2. Update .dev-shell/container.conf (if using dev-shell runners):"
echo "     DEV_SHELL_CONTAINER_IMAGE=my-project-dev:latest"
echo "  3. Build the image:"
echo "     docker build -t my-project-dev:latest $TARGET_REPO"
echo "  4. Test with:"
echo "     docker run --rm -v \$PWD:/workspace my-project-dev:latest python --version"
echo ""
echo "Note: requirements.txt is at $REQUIREMENTS"
echo "      Python version detected: $PYTHON_VERSION"
echo "      Python path: $PYTHON_CMD"
echo "      Reproduction guide: HOWTO_REPRODUCE.md (for reviewers)"
