@echo off
setlocal

set "DEV_SHELL_SUBSYSTEM_VALUE=%DEV_SHELL_SUBSYSTEM%"
set "DEV_SHELL_DEFAULT_VENV_VALUE=%DEV_SHELL_DEFAULT_VENV%"
set "DEV_SHELL_VENV_SUFFIX_VALUE=%DEV_SHELL_VENV_SUFFIX%"
set "DEV_SHELL_ACTIVE_VENV_KIND_VALUE=%DEV_SHELL_ACTIVE_VENV_KIND%"
set "DEV_SHELL_ACTIVE_VENV_PATH_VALUE=%DEV_SHELL_ACTIVE_VENV_PATH%"

if not defined DEV_SHELL_SUBSYSTEM_VALUE set "DEV_SHELL_SUBSYSTEM_VALUE=WINDOWS"
if not defined DEV_SHELL_VENV_SUFFIX_VALUE set "DEV_SHELL_VENV_SUFFIX_VALUE=win"
if not defined DEV_SHELL_DEFAULT_VENV_VALUE set "DEV_SHELL_DEFAULT_VENV_VALUE=%USERPROFILE%\.venv-%DEV_SHELL_VENV_SUFFIX_VALUE%"

if not defined DEV_SHELL_ACTIVE_VENV_KIND_VALUE (
    if exist "%CD%\.venv-%DEV_SHELL_VENV_SUFFIX_VALUE%\Scripts\activate.bat" (
        set "DEV_SHELL_ACTIVE_VENV_KIND_VALUE=local"
        set "DEV_SHELL_ACTIVE_VENV_PATH_VALUE=%CD%\.venv-%DEV_SHELL_VENV_SUFFIX_VALUE%"
    ) else if exist "%CD%\.venv\Scripts\activate.bat" (
        set "DEV_SHELL_ACTIVE_VENV_KIND_VALUE=local"
        set "DEV_SHELL_ACTIVE_VENV_PATH_VALUE=%CD%\.venv"
    ) else if exist "%DEV_SHELL_DEFAULT_VENV_VALUE%\Scripts\activate.bat" (
        set "DEV_SHELL_ACTIVE_VENV_KIND_VALUE=default"
        set "DEV_SHELL_ACTIVE_VENV_PATH_VALUE=%DEV_SHELL_DEFAULT_VENV_VALUE%"
    ) else if exist "%USERPROFILE%\.venv\Scripts\activate.bat" (
        set "DEV_SHELL_ACTIVE_VENV_KIND_VALUE=default"
        set "DEV_SHELL_ACTIVE_VENV_PATH_VALUE=%USERPROFILE%\.venv"
    )
)

echo DEV_SHELL_SUBSYSTEM=%DEV_SHELL_SUBSYSTEM_VALUE%
echo DEV_SHELL_DEFAULT_VENV=%DEV_SHELL_DEFAULT_VENV_VALUE%
echo DEV_SHELL_ACTIVE_VENV_KIND=%DEV_SHELL_ACTIVE_VENV_KIND_VALUE%
echo DEV_SHELL_ACTIVE_VENV_PATH=%DEV_SHELL_ACTIVE_VENV_PATH_VALUE%
echo VIRTUAL_ENV=%VIRTUAL_ENV%

endlocal