@echo off
REM generate-dockerfile.cmd - Generate a Dockerfile template from the discovered Python venv with pinned package versions.

setlocal enabledelayedexpansion

REM Set default target repo to current directory
set "TARGET_REPO=%~1"
if "%TARGET_REPO%"=="" set "TARGET_REPO=."

REM Resolve to absolute path
for /f "tokens=*" %%A in ('cd /d "%TARGET_REPO%" ^& cd') do set "TARGET_REPO=%%A"

REM Verify the target is a directory
if not exist "%TARGET_REPO%" (
    echo Error: Target repository not found: %TARGET_REPO%
    exit /b 1
)

REM Create .dev-shell directory if it doesn't exist
set "DEV_SHELL_DIR=%TARGET_REPO%\.dev-shell"
if not exist "%DEV_SHELL_DIR%" mkdir "%DEV_SHELL_DIR%"

REM Determine the subsystem (default to UCRT64 if not set)
if "%MSYSTEM%"=="" set "MSYSTEM=UCRT64"

REM Helper function to find preferred venv (using set /p with file redirection)
REM Check repo-local .venv-<subsystem>
set "VENV_PYTHON="
if exist "%TARGET_REPO%\.venv-%MSYSTEM%\Scripts\python.exe" (
    set "VENV_PYTHON=%TARGET_REPO%\.venv-%MSYSTEM%\Scripts\python.exe"
    echo Using venv: !VENV_PYTHON!
    goto venv_found
)

REM Check repo-local .venv
if exist "%TARGET_REPO%\.venv\Scripts\python.exe" (
    set "VENV_PYTHON=%TARGET_REPO%\.venv\Scripts\python.exe"
    echo Using venv: !VENV_PYTHON!
    goto venv_found
)

REM Check global .venv-<subsystem>
if exist "%USERPROFILE%\.venv-%MSYSTEM%\Scripts\python.exe" (
    set "VENV_PYTHON=%USERPROFILE%\.venv-%MSYSTEM%\Scripts\python.exe"
    echo Using venv: !VENV_PYTHON!
    goto venv_found
)

REM Check global .venv
if exist "%USERPROFILE%\.venv\Scripts\python.exe" (
    set "VENV_PYTHON=%USERPROFILE%\.venv\Scripts\python.exe"
    echo Using venv: !VENV_PYTHON!
    goto venv_found
)

REM If no venv found, try system Python
where /q python
if errorlevel 1 (
    echo Error: No Python venv found and no system Python available.
    echo Checked:
    echo   - %TARGET_REPO%\.venv-%MSYSTEM%
    echo   - %TARGET_REPO%\.venv
    echo   - %USERPROFILE%\.venv-%MSYSTEM%
    echo   - %USERPROFILE%\.venv
    exit /b 1
)

set "VENV_PYTHON=python"
echo Using system Python

:venv_found

REM Get Python version
for /f "tokens=2" %%A in ('!VENV_PYTHON! --version 2^>^&1') do set "PYTHON_VERSION=%%A"

REM Freeze current venv packages
set "REQUIREMENTS=%DEV_SHELL_DIR%\requirements.txt"
echo Exporting packages from !VENV_PYTHON! to %REQUIREMENTS%...
!VENV_PYTHON! -m pip freeze > "%REQUIREMENTS%"
if errorlevel 1 (
    echo Error: Failed to export packages from venv.
    exit /b 1
)

REM Count packages
for /f %%A in ('find /c /v "" ^< "%REQUIREMENTS%"') do set "PACKAGE_COUNT=%%A"
echo Exported %PACKAGE_COUNT% packages.

REM Generate Dockerfile template
set "DOCKERFILE=%DEV_SHELL_DIR%\Dockerfile"
echo Generating %DOCKERFILE%...

(
    echo # Dockerfile - Generated by generate-dockerfile.cmd
    echo # This image freezes the Python environment for reproducible paper experiments.
    echo # Build: docker build -t my-project-dev:latest .
    echo # Run:   run-container.cmd python scripts\run_experiment.py
    echo.
    echo ARG PYTHON_VERSION=3.12
    echo FROM python:${PYTHON_VERSION}-slim
    echo.
    echo WORKDIR /workspace
    echo.
    echo # Copy requirements and install pinned packages
    echo COPY .dev-shell\requirements.txt .
    echo RUN pip install --no-cache-dir -r requirements.txt
    echo.
    echo # Copy repo contents
    echo COPY . .
    echo.
    echo # Set up entry point (optional, can be overridden^)
    echo # ENTRYPOINT ["python"]
    echo # CMD ["--version"]
) > "%DOCKERFILE%"

if errorlevel 1 (
    echo Error: Failed to create Dockerfile.
    exit /b 1
)

REM Find the framework's templates directory
for /d %%A in ("%~dp0..\..\..") do set "SCRIPT_REPO_ROOT=%%~fA"
set "TEMPLATES_DIR=%SCRIPT_REPO_ROOT%\templates"

REM Copy HOWTO_REPRODUCE.md if it exists
set "HOWTO_SRC=%TEMPLATES_DIR%\HOWTO_REPRODUCE.md"
set "HOWTO_DST=%TARGET_REPO%\HOWTO_REPRODUCE.md"
if exist "%HOWTO_SRC%" (
    copy /y "%HOWTO_SRC%" "%HOWTO_DST%" >nul
    echo Done.
    echo Copied HOWTO_REPRODUCE.md to: %HOWTO_DST%
) else (
    echo Done.
    echo Note: HOWTO_REPRODUCE.md template not found at %TEMPLATES_DIR% (optional^)
)

echo.
echo Dockerfile created at: %DOCKERFILE%
echo.
echo Next steps:
echo   1. Edit %DOCKERFILE% to customize the base image or add dependencies
echo   2. Update .dev-shell\container.conf (if using dev-shell runners^):
echo      DEV_SHELL_CONTAINER_IMAGE=my-project-dev:latest
echo   3. Build the image:
echo      docker build -t my-project-dev:latest %TARGET_REPO%
echo   4. Test with:
echo      docker run --rm -v %%cd%%:/workspace my-project-dev:latest python --version
echo.
echo Note: requirements.txt is at %REQUIREMENTS%
echo       Python version detected: %PYTHON_VERSION%
echo       Python path: !VENV_PYTHON!
echo       Reproduction guide: HOWTO_REPRODUCE.md (for reviewers^)

endlocal
exit /b 0
