#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
import sys


REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = REPO_ROOT / "catalog.md"


@dataclass(frozen=True)
class Entry:
    command: str
    path: str
    description: str


CMD_STARTERS = {
    "shells/windows/cmd/clang64.cmd",
    "shells/windows/cmd/git-bash.cmd",
    "shells/windows/cmd/mingw64.cmd",
    "shells/windows/cmd/msys64.cmd",
    "shells/windows/cmd/sagemath.cmd",
    "shells/windows/cmd/ucrt64.cmd",
    "shells/windows/cmd/vs-dev.cmd",
    "shells/windows/cmd/win-admin.cmd",
    "shells/windows/cmd/win-choco.cmd",
    "shells/windows/cmd/win-dev.cmd",
    "shells/windows/cmd/win-dev-perl.cmd",
    "shells/windows/cmd/win-perl.cmd",
    "shells/windows/cmd/win.cmd",
}

SH_STARTERS = {
    "shells/bash/clang64/lib/startup-wrapper.sh",
    "shells/bash/mingw64/lib/startup-wrapper.sh",
    "shells/bash/msys2/lib/startup-wrapper.sh",
    "shells/bash/ucrt64/lib/startup-wrapper.sh",
}

DESCRIPTION_OVERRIDES = {}


def normalize(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def quoted(text: str) -> str:
    return f"`{text}`"


def read_description(path: Path) -> str | None:
    relative_path = normalize(path)
    if relative_path in DESCRIPTION_OVERRIDES:
        return DESCRIPTION_OVERRIDES[relative_path]

    comment_lines: list[str] = []
    with path.open("r", encoding="utf-8", errors="ignore") as handle:
        for index, line in enumerate(handle):
            if index >= 14:
                break

            stripped = line.strip()
            if not stripped:
                if comment_lines:
                    break
                continue

            if stripped.startswith("#!"):
                continue

            comment = None
            if stripped.startswith("::"):
                comment = stripped[2:].strip()
            elif stripped.lower().startswith("rem "):
                comment = stripped[4:].strip()
            elif stripped.startswith("#"):
                comment = stripped[1:].strip()

            if comment is None:
                if comment_lines:
                    break
                continue

            if not comment:
                continue

            lower_comment = comment.lower()
            if lower_comment.startswith("usage:"):
                break
            if set(comment) <= {"-", "="}:
                continue

            comment_lines.append(comment)

    if not comment_lines:
        return None

    first = comment_lines[0]
    first = re.sub(r"^[A-Za-z0-9_.-]+\s+-\s+", "", first)
    first = first.rstrip(".")
    if not first:
        return None
    return first[0].upper() + first[1:] + "."


def collect_entries(pattern: str) -> list[Path]:
    return sorted(REPO_ROOT.glob(pattern))


def build_entry(path: Path) -> Entry:
    relative_path = normalize(path)
    description = read_description(path)
    if description is None:
        raise ValueError(f"Missing description for {relative_path}")

    return Entry(command=path.name, path=relative_path, description=description)


def entry_sort_key(entry: Entry) -> tuple[str, str]:
    return (entry.command.lower(), entry.path.lower())


def render_table(entries: list[Entry]) -> list[str]:
    lines = ["| Command | Path | Description |", "| --- | --- | --- |"]
    for entry in sorted(entries, key=entry_sort_key):
        lines.append(
            "| "
            f"{quoted(entry.command)} | {quoted(entry.path)} | {entry.description} |"
        )
    return lines


def generate_catalog() -> str:
    cmd_paths = collect_entries("shells/**/*.cmd")
    sh_paths = collect_entries("shells/**/*.sh")

    cmd_starters = [build_entry(path) for path in cmd_paths if normalize(path) in CMD_STARTERS]
    cmd_utilities = [build_entry(path) for path in cmd_paths if normalize(path) not in CMD_STARTERS]
    sh_starters = [build_entry(path) for path in sh_paths if normalize(path) in SH_STARTERS]
    sh_utilities = [build_entry(path) for path in sh_paths if normalize(path) not in SH_STARTERS]

    lines = [
        "# Command Catalog",
        "",
        "This file is generated by `build-catalog.cmd`, `build-catalog.sh`, or `tools/generate_catalog.py`.",
        "Run `dev-catalog.cmd` from Windows command shells or `dev-catalog.sh` from bash shells to print this catalog.",
        "",
        "## CMD Shell Starters",
        "",
        *render_table(cmd_starters),
        "",
        "## CMD Utility Commands",
        "",
        *render_table(cmd_utilities),
        "",
        "## SH Shell Starters",
        "",
        *render_table(sh_starters),
        "",
        "## SH Utility Commands",
        "",
        *render_table(sh_utilities),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    catalog_text = generate_catalog()
    CATALOG_PATH.write_text(catalog_text, encoding="utf-8")
    print(f"Wrote {CATALOG_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())